### PR TITLE
Implement hashCode in Color

### LINKED ISSUE #7: Color implements equals operator but not hashCode
The Color class implements equals operator (==) but not hashCode

### PR DESCRIPTION
**Pull request by ilikerobots**
Fixes #7

### CODE REVIEW

**Comment by kevmoo** [comment]
We need to loop this through the components internally, so it might take a while.

Thanks!

**Comment by ilikerobots** [comment]
Np. :metal:

**Comment by kevmoo** [comment]
You just made my day. :-)

**Comment by nshahan** [comment]
We are currently not setup to merge the pull requests from this preview repo but I thank you. A hashCode method was added in a recent update.

**Pull request closed without merging**
